name: Space ERP back-end CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v5.0.0
        with: 
          context: .
          file: ./docker/Dockerfile_prod
          push: true
          tags: | 
            artearenahub/space-erp-backend:0.0.${{github.run_number}}
            artearenahub/space-erp-backend:latest
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
